### ISSUE TITLE
Provide common code for zeromq filter and output

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-zeromq#5]
(This issue was originally filed by @suyograo at https://github.com/elastic/logstash/issues/2434)

---

logstash-filter-zeromq and logstash-output-zeromq are using [utils/zeromq.rb](https://github.com/logstash-plugins/logstash-filter-zeromq/blob/master/lib/logstash/util/zeromq.rb) file which was duplicated during beta1 as part of https://github.com/elasticsearch/logstash/issues/2055. Previously, before the plugin separation, they shared the same file. We know have to DRY this up to a new plugin like https://github.com/logstash-plugins/logstash-mixin-aws which has common utils code for EC2 input and output.

**Comment by breml** [comment]
@avishai-ish-shalom This issue has been resolved with commit https://github.com/logstash-plugins/logstash-filter-zeromq/commit/1c672d2a24fbca82a11d26517d8664806219d579
